### PR TITLE
Modify chapter 1 related content based on rev8

### PR DESCRIPTION
**Pull request by ybzhaoINxjtu**
1.rename and add picture of chapter 1
2.modify chapter 1

### CODE REVIEW

**Comment by ranxian** [comment]
Did this PR reflect all updates of rev8 from rev7? @ybzhaoINxjtu

**Comment by ybzhaoINxjtu** [comment]
Yes, it is

**Comment by ybzhaoINxjtu** [comment]
Yes, it is

**Comment by ybzhaoINxjtu** [comment]
Yes, it is

**Comment by ybzhaoINxjtu** [comment]
Yes, it is

**Comment by ybzhaoINxjtu** [comment]
Yes, it is

**Comment by ybzhaoINxjtu** [comment]
Yes, it is

**Comment by ybzhaoINxjtu** [comment]
Yes, it is

**Comment by ybzhaoINxjtu** [comment]
Yes, it is

**Comment by ybzhaoINxjtu** [comment]
Yes, it is

**Comment by ranxian** [comment]
Thanks. Please do not reply so many times @ybzhaoINxjtu

**Comment by ybzhaoINxjtu** [comment]
Either my network or browser is crazy ! Maybe the later one since it does not respond to my click on 'comment' . = =!

**Comment by ybzhaoINxjtu** [comment]
Either my network or browser is crazy ! Maybe the later one since it does not respond to my click on 'comment' . = =!

**Comment by ranxian** [comment]
I think every time you hit the bottom it will actually make the request, so please don't hit the bottom more than once even if it does not respond.

**Comment by ybzhaoINxjtu** [comment]
Since the original PR has been closed, I guess I need to PR again, right?

**Comment by ranxian** [comment]
I have just re-opened and merged the PR. Thanks for pointing out

**Comment by ybzhaoINxjtu** [comment]
^_^

**Pull request merged**
